PC.SAV: PC.OBJ RADASC.OBJ DASC.OBJ PSERV.OBJ PPFUNC.OBJ PPUNL.OBJ ONOFF.OBJ KEY.OBJ TIME.OBJ LINE.OBJ SEARCH.OBJ TAB.OBJ DEVICE.OBJ PULLDN.OBJ PAL.OBJ GETDIR.OBJ UNPACK.OBJ SORT.OBJ CMPDIR.OBJ SYNTAX.OBJ DIALOG.OBJ DIAL.OBJ SELECT.OBJ MATCH.OBJ COMMON.OBJ SCNMSK.OBJ HELP.OBJ EDIT.OBJ VIEW.OBJ PRO.OBJ COPY.OBJ COPY2.OBJ RMATCH.OBJ DELETE.OBJ HR.OBJ SAVINI.OBJ EXT.OBJ INIINI.OBJ INIEXT.OBJ PPLOA.OBJ PP.OBJ
	echo todo link

%.OBJ: %.MAC
	./macro11 $< -o $@